
DROP TABLE IF EXISTS mrc_countries;

CREATE TABLE mrc_countries(
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	fips CHAR(2) NOT NULL UNIQUE,
	iso CHAR(2) NOT NULL,
	tld CHAR(3) NOT NULL,
	name VARCHAR(32) NOT NULL,

	INDEX ix_countries_iso (iso ASC),
	INDEX ix_countries_tld (tld ASC)
)CHARSET='utf8' COLLATE='utf8_general_ci';


INSERT INTO mrc_countries(id, fips, iso, tld, name) VALUES
(1,'AA','AW','.aw','Aruba'),
(2,'AC','AG','.ag','Antigua and Barbuda'),
(3,'AE','AE','.ae','United Arab Emirates'),
(4,'AF','AF','.af','Afghanistan'),
(5,'AG','DZ','.dz','Algeria'),
(6,'AJ','AZ','.az','Azerbaijan'),
(7,'AL','AL','.al','Albania'),
(8,'AM','AM','.am','Armenia'),
(9,'AN','AD','.ad','Andorra'),
(10,'AO','AO','.ao','Angola'),
(11,'AQ','AS','.as','American Samoa'),
(12,'AR','AR','.ar','Argentina'),
(13,'AS','AU','.au','Australia'),
(14,'AT','-','-','Ashmore and Cartier Islands'),
(15,'AU','AT','.at','Austria'),
(16,'AV','AI','.ai','Anguilla'),
(17,'AX','AX','.ax','Åland Islands'),
(18,'AY','AQ','.aq','Antarctica'),
(19,'BA','BH','.bh','Bahrain'),
(20,'BB','BB','.bb','Barbados'),
(21,'BC','BW','.bw','Botswana'),
(22,'BD','BM','.bm','Bermuda'),
(23,'BE','BE','.be','Belgium'),
(24,'BF','BS','.bs','Bahamas, The'),
(25,'BG','BD','.bd','Bangladesh'),
(26,'BH','BZ','.bz','Belize'),
(27,'BK','BA','.ba','Bosnia and Herzegovina'),
(28,'BL','BO','.bo','Bolivia'),
(29,'BM','MM','.mm','Myanmar'),
(30,'BN','BJ','.bj','Benin'),
(31,'BO','BY','.by','Belarus'),
(32,'BP','SB','.sb','Solomon Islands'),
(33,'BQ','-','-','Navassa Island'),
(34,'BR','BR','.br','Brazil'),
(35,'BS','-','-','Bassas da India'),
(36,'BT','BT','.bt','Bhutan'),
(37,'BU','BG','.bg','Bulgaria'),
(38,'BV','BV','.bv','Bouvet Island'),
(39,'BX','BN','.bn','Brunei'),
(40,'BY','BI','.bi','Burundi'),
(41,'CA','CA','.ca','Canada'),
(42,'CB','KH','.kh','Cambodia'),
(43,'CD','TD','.td','Chad'),
(44,'CE','LK','.lk','Sri Lanka'),
(45,'CF','CG','.cg','Congo, Republic of the'),
(46,'CG','CD','.cd','Congo, Democratic Republic of the'),
(47,'CH','CN','.cn','China'),
(48,'CI','CL','.cl','Chile'),
(49,'CJ','KY','.ky','Cayman Islands'),
(50,'CK','CC','.cc','Cocos (Keeling) Islands'),
(51,'CM','CM','.cm','Cameroon'),
(52,'CN','KM','.km','Comoros'),
(53,'CO','CO','.co','Colombia'),
(54,'CQ','MP','.mp','Northern Mariana Islands'),
(55,'CR','-','-','Coral Sea Islands'),
(56,'CS','CR','.cr','Costa Rica'),
(57,'CT','CF','.cf','Central African Republic'),
(58,'CU','CU','.cu','Cuba'),
(59,'CV','CV','.cv','Cape Verde'),
(60,'CW','CK','.ck','Cook Islands'),
(61,'CY','CY','.cy','Cyprus'),
(62,'DA','DK','.dk','Denmark'),
(63,'DJ','DJ','.dj','Djibouti'),
(64,'DO','DM','.dm','Dominica'),
(65,'DQ','UM','-','Jarvis Island'),
(66,'DR','DO','.do','Dominican Republic'),
(67,'DX','-','-','Dhekelia Sovereign Base Area'),
(68,'EC','EC','.ec','Ecuador'),
(69,'EG','EG','.eg','Egypt'),
(70,'EI','IE','.ie','Ireland'),
(71,'EK','GQ','.gq','Equatorial Guinea'),
(72,'EN','EE','.ee','Estonia'),
(73,'ER','ER','.er','Eritrea'),
(74,'ES','SV','.sv','El Salvador'),
(75,'ET','ET','.et','Ethiopia'),
(76,'EU','-','-','Europa Island'),
(77,'EZ','CZ','.cz','Czech Republic'),
(78,'FG','GF','.gf','French Guiana'),
(79,'FI','FI','.fi','Finland'),
(80,'FJ','FJ','.fj','Fiji'),
(81,'FK','FK','.fk','Falkland Islands (Islas Malvinas)'),
(82,'FM','FM','.fm','Micronesia, Federated States of'),
(83,'FO','FO','.fo','Faroe Islands'),
(84,'FP','PF','.pf','French Polynesia'),
(85,'FQ','UM','-','Baker Island'),
(86,'FR','FR','.fr','France'),
(87,'FS','TF','.tf','French Southern and Antarctic Lands'),
(88,'GA','GM','.gm','Gambia, The'),
(89,'GB','GA','.ga','Gabon'),
(90,'GG','GE','.ge','Georgia'),
(91,'GH','GH','.gh','Ghana'),
(92,'GI','GI','.gi','Gibraltar'),
(93,'GJ','GD','.gd','Grenada'),
(94,'GK','-','.gg','Guernsey'),
(95,'GL','GL','.gl','Greenland'),
(96,'GM','DE','.de','Germany'),
(97,'GO','-','-','Glorioso Islands'),
(98,'GP','GP','.gp','Guadeloupe'),
(99,'GQ','GU','.gu','Guam'),
(100,'GR','GR','.gr','Greece'),
(101,'GT','GT','.gt','Guatemala'),
(102,'GV','GN','.gn','Guinea'),
(103,'GY','GY','.gy','Guyana'),
(104,'GZ','-','-','Gaza Strip'),
(105,'HA','HT','.ht','Haiti'),
(106,'HK','HK','.hk','Hong Kong'),
(107,'HM','HM','.hm','Heard Island and McDonald Islands'),
(108,'HO','HN','.hn','Honduras'),
(109,'HQ','UM','-','Howland Island'),
(110,'HR','HR','.hr','Croatia'),
(111,'HU','HU','.hu','Hungary'),
(112,'IC','IS','.is','Iceland'),
(113,'ID','ID','.id','Indonesia'),
(114,'IM','IM','.im','Isle of Man'),
(115,'IN','IN','.in','India'),
(116,'IO','IO','.io','British Indian Ocean Territory'),
(117,'IP','-','-','Clipperton Island'),
(118,'IR','IR','.ir','Iran'),
(119,'IS','IL','.il','Israel'),
(120,'IT','IT','.it','Italy'),
(121,'IV','CI','.ci','Cote d''Ivoire'),
(122,'IZ','IQ','.iq','Iraq'),
(123,'JA','JP','.jp','Japan'),
(124,'JE','JE','.je','Jersey'),
(125,'JM','JM','.jm','Jamaica'),
(126,'JN','SJ','-','Jan Mayen'),
(127,'JO','JO','.jo','Jordan'),
(128,'JQ','UM','-','Johnston Atoll'),
(129,'JU','-','-','Juan de Nova Island'),
(130,'KE','KE','.ke','Kenya'),
(131,'KG','KG','.kg','Kyrgyzstan'),
(132,'KN','KP','.kp','Korea, North'),
(133,'KQ','UM','-','Kingman Reef'),
(134,'KR','KI','.ki','Kiribati'),
(135,'KS','KR','.kr','Korea, South'),
(136,'KT','CX','.cx','Christmas Island'),
(137,'KU','KW','.kw','Kuwait'),
(138,'KV','KV','-','Kosovo'),
(139,'KZ','KZ','.kz','Kazakhstan'),
(140,'LA','LA','.la','Laos'),
(141,'LE','LB','.lb','Lebanon'),
(142,'LG','LV','.lv','Latvia'),
(143,'LH','LT','.lt','Lithuania'),
(144,'LI','LR','.lr','Liberia'),
(145,'LO','SK','.sk','Slovakia'),
(146,'LQ','UM','-','Palmyra Atoll'),
(147,'LS','LI','.li','Liechtenstein'),
(148,'LT','LS','.ls','Lesotho'),
(149,'LU','LU','.lu','Luxembourg'),
(150,'LY','LY','.ly','Libyan Arab'),
(151,'MA','MG','.mg','Madagascar'),
(152,'MB','MQ','.mq','Martinique'),
(153,'MC','MO','.mo','Macau'),
(154,'MD','MD','.md','Moldova, Republic of'),
(155,'MF','YT','.yt','Mayotte'),
(156,'MG','MN','.mn','Mongolia'),
(157,'MH','MS','.ms','Montserrat'),
(158,'MI','MW','.mw','Malawi'),
(159,'MJ','ME','.me','Montenegro'),
(160,'MK','MK','.mk','The Former Yugoslav Republic of Macedonia'),
(161,'ML','ML','.ml','Mali'),
(162,'MN','MC','.mc','Monaco'),
(163,'MO','MA','.ma','Morocco'),
(164,'MP','MU','.mu','Mauritius'),
(165,'MQ','UM','-','Midway Islands'),
(166,'MR','MR','.mr','Mauritania'),
(167,'MT','MT','.mt','Malta'),
(168,'MU','OM','.om','Oman'),
(169,'MV','MV','.mv','Maldives'),
(170,'MX','MX','.mx','Mexico'),
(171,'MY','MY','.my','Malaysia'),
(172,'MZ','MZ','.mz','Mozambique'),
(173,'NC','NC','.nc','New Caledonia'),
(174,'NE','NU','.nu','Niue'),
(175,'NF','NF','.nf','Norfolk Island'),
(176,'NG','NE','.ne','Niger'),
(177,'NH','VU','.vu','Vanuatu'),
(178,'NI','NG','.ng','Nigeria'),
(179,'NL','NL','.nl','Netherlands'),
(180,'NM','','','No Man''s Land'),
(181,'NO','NO','.no','Norway'),
(182,'NP','NP','.np','Nepal'),
(183,'NR','NR','.nr','Nauru'),
(184,'NS','SR','.sr','Suriname'),
(185,'NT','AN','.an','Netherlands Antilles'),
(186,'NU','NI','.ni','Nicaragua'),
(187,'NZ','NZ','.nz','New Zealand'),
(188,'PA','PY','.py','Paraguay'),
(189,'PC','PN','.pn','Pitcairn Islands'),
(190,'PE','PE','.pe','Peru'),
(191,'PF','-','-','Paracel Islands'),
(192,'PG','-','-','Spratly Islands'),
(193,'PK','PK','.pk','Pakistan'),
(194,'PL','PL','.pl','Poland'),
(195,'PM','PA','.pa','Panama'),
(196,'PO','PT','.pt','Portugal'),
(197,'PP','PG','.pg','Papua New Guinea'),
(198,'PS','PW','.pw','Palau'),
(199,'PU','GW','.gw','Guinea-Bissau'),
(200,'QA','QA','.qa','Qatar'),
(201,'RE','RE','.re','Reunion'),
(202,'RI','RS','.rs','Serbia'),
(203,'RM','MH','.mh','Marshall Islands'),
(204,'RN','MF','-','Saint Martin'),
(205,'RO','RO','.ro','Romania'),
(206,'RP','PH','.ph','Philippines'),
(207,'RQ','PR','.pr','Puerto Rico'),
(208,'RS','RU','.ru','Russia'),
(209,'RW','RW','.rw','Rwanda'),
(210,'SA','SA','.sa','Saudi Arabia'),
(211,'SB','PM','.pm','Saint Pierre and Miquelon'),
(212,'SC','KN','.kn','Saint Kitts and Nevis'),
(213,'SE','SC','.sc','Seychelles'),
(214,'SF','ZA','.za','South Africa'),
(215,'SG','SN','.sn','Senegal'),
(216,'SH','SH','.sh','Saint Helena'),
(217,'SI','SI','.si','Slovenia'),
(218,'SL','SL','.sl','Sierra Leone'),
(219,'SM','SM','.sm','San Marino'),
(220,'SN','SG','.sg','Singapore'),
(221,'SO','SO','.so','Somalia'),
(222,'SP','ES','.es','Spain'),
(223,'-','SS','.ss','South Sudan'),
(224,'ST','LC','.lc','Saint Lucia'),
(225,'SU','SD','.sd','Sudan'),
(226,'SV','SJ','.sj','Svalbard'),
(227,'SW','SE','.se','Sweden'),
(228,'SX','GS','.gs','South Georgia and the Islands'),
(229,'SY','SY','.sy','Syrian Arab Republic'),
(230,'SZ','CH','.ch','Switzerland'),
(231,'TD','TT','.tt','Trinidad and Tobago'),
(232,'TE','-','-','Tromelin Island'),
(233,'TH','TH','.th','Thailand'),
(234,'TI','TJ','.tj','Tajikistan'),
(235,'TK','TC','.tc','Turks and Caicos Islands'),
(236,'TL','TK','.tk','Tokelau'),
(237,'TN','TO','.to','Tonga'),
(238,'TO','TG','.tg','Togo'),
(239,'TP','ST','.st','Sao Tome and Principe'),
(240,'TS','TN','.tn','Tunisia'),
(241,'TT','TL','.tl','East Timor'),
(242,'TU','TR','.tr','Turkey'),
(243,'TV','TV','.tv','Tuvalu'),
(244,'TW','TW','.tw','Taiwan'),
(245,'TX','TM','.tm','Turkmenistan'),
(246,'TZ','TZ','.tz','Tanzania, United Republic of'),
(247,'UG','UG','.ug','Uganda'),
(248,'UK','GB','.uk','United Kingdom'),
(249,'UP','UA','.ua','Ukraine'),
(250,'US','US','.us','United States'),
(251,'UV','BF','.bf','Burkina Faso'),
(252,'UY','UY','.uy','Uruguay'),
(253,'UZ','UZ','.uz','Uzbekistan'),
(254,'VC','VC','.vc','Saint Vincent and the Grenadines'),
(255,'VE','VE','.ve','Venezuela'),
(256,'VI','VG','.vg','British Virgin Islands'),
(257,'VM','VN','.vn','Vietnam'),
(258,'VQ','VI','.vi','Virgin Islands (US)'),
(259,'VT','VA','.va','Holy See (Vatican City)'),
(260,'WA','NA','.na','Namibia'),
(261,'WE','-','-','West Bank'),
(262,'WF','WF','.wf','Wallis and Futuna'),
(263,'WI','EH','.eh','Western Sahara'),
(264,'WQ','UM','-','Wake Island'),
(265,'WS','WS','.ws','Samoa'),
(266,'WZ','SZ','.sz','Swaziland'),
(267,'YI','CS','.yu','Serbia and Montenegro'),
(268,'YM','YE','.ye','Yemen'),
(269,'ZA','ZM','.zm','Zambia'),
(270,'ZI','ZW','.zw','Zimbabwe');