
DROP TABLE IF EXISTS mrc_user_passwords;

CREATE TABLE mrc_user_passwords(

	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL UNIQUE,
	password CHAR(40) NOT NULL,
	rand1 VARCHAR(40) NOT NULL,
	rand2 VARCHAR(40) NOT NULL

)CHARSET='utf8' COLLATE='utf8_general_ci';

